In [1]:
import pandas as pd
import numpy as np 
import spacy

In [2]:
df1 = pd.read_csv("../Data/Sentiment/twitter_data.csv")
df1

                                               clean_text  category
0       when modi promised “minimum government maximum...      -1.0
1       talk all the nonsense and continue all the dra...       0.0
2       what did just say vote for modi  welcome bjp t...       1.0
3       asking his supporters prefix chowkidar their n...       1.0
4       answer who among these the most powerful world...       1.0
...                                                   ...       ...
162975  why these 456 crores paid neerav modi not reco...      -1.0
162976  dear rss terrorist payal gawar what about modi...      -1.0
162977  did you cover her interaction forum where she ...       0.0
162978  there big project came into india modi dream p...       0.0
162979  have you ever listen about like gurukul where ...       1.0

[162980 rows x 2 columns]

In [3]:
df1 = df1.rename(columns={
    "clean_text": "text",
    "category": "label"
})
df1

                                                     text  label
0       when modi promised “minimum government maximum...   -1.0
1       talk all the nonsense and continue all the dra...    0.0
2       what did just say vote for modi  welcome bjp t...    1.0
3       asking his supporters prefix chowkidar their n...    1.0
4       answer who among these the most powerful world...    1.0
...                                                   ...    ...
162975  why these 456 crores paid neerav modi not reco...   -1.0
162976  dear rss terrorist payal gawar what about modi...   -1.0
162977  did you cover her interaction forum where she ...    0.0
162978  there big project came into india modi dream p...    0.0
162979  have you ever listen about like gurukul where ...    1.0

[162980 rows x 2 columns]

In [4]:
df2 = pd.read_json("../Data/Intent/nlu-benchmark-master/2017-06-custom-intent-engines/AddToPlaylist/train_AddToPlaylist_full.json" ,  encoding="utf-8")
df2

                                          AddToPlaylist
0     {'data': [{'text': 'Add another '}, {'text': '...
1     {'data': [{'text': 'add '}, {'text': 'clem bur...
2     {'data': [{'text': 'Add '}, {'text': 'Live fro...
3     {'data': [{'text': 'add '}, {'text': 'Unite an...
4     {'data': [{'text': 'Add '}, {'text': 'track', ...
...                                                 ...
1937  {'data': [{'text': 'I'd like to put '}, {'text...
1938  {'data': [{'text': 'add '}, {'text': 'sweets e...
1939  {'data': [{'text': 'Add '}, {'text': 'ana caro...
1940  {'data': [{'text': 'Add '}, {'text': 'decade i...
1941  {'data': [{'text': 'add '}, {'text': 'artist',...

[1942 rows x 1 columns]

#### Extracting Function

In [5]:
def extract(text , label):
    texts=[]
    for text in df2['AddToPlaylist']:
        for txt in text['data']:
             texts.append(txt['text'])
    return pd.DataFrame({"text": texts , 'label':label})

In [6]:
df2_clean = extract(df2, "AddToPlaylist")
df2_clean

                 text          label
0        Add another   AddToPlaylist
1                song  AddToPlaylist
2             to the   AddToPlaylist
3      Cita Romántica  AddToPlaylist
4          playlist.   AddToPlaylist
...               ...            ...
11715             to   AddToPlaylist
11716              my  AddToPlaylist
11717                  AddToPlaylist
11718   friendesemana  AddToPlaylist
11719        playlist  AddToPlaylist

[11720 rows x 2 columns]

In [7]:
df3 = pd.read_json("../Data/Intent/nlu-benchmark-master/2017-06-custom-intent-engines/BookRestaurant/train_BookRestaurant_full.json" ,  encoding="utf-8")
df3

                                         BookRestaurant
0     {'data': [{'text': 'book '}, {'text': 'The Mid...
1     {'data': [{'text': 'Book a table at '}, {'text...
2     {'data': [{'text': 'I'd like to eat at a '}, {...
3     {'data': [{'text': 'I have a party of '}, {'te...
4     {'data': [{'text': 'Please make a '}, {'text':...
...                                                 ...
1968  {'data': [{'text': 'I would like to book a '},...
1969  {'data': [{'text': 'Book a table for '}, {'tex...
1970  {'data': [{'text': 'Book a '}, {'text': 'resta...
1971  {'data': [{'text': 'Book a '}, {'text': 'bistr...
1972  {'data': [{'text': 'Book a '}, {'text': 'brass...

[1973 rows x 1 columns]

In [8]:
def extract(text , label):
    texts=[]
    for text in df3['BookRestaurant']:
        for txt in text['data']:
             texts.append(txt['text'])
    return pd.DataFrame({"text": texts , 'label':label})

In [9]:
df3_clean = extract(df3, "BooksRestaurant")
df3_clean

                  text            label
0                book   BooksRestaurant
1      The Middle East  BooksRestaurant
2                       BooksRestaurant
3           restaurant  BooksRestaurant
4                  in   BooksRestaurant
...                ...              ...
13388              at   BooksRestaurant
13389            18:28  BooksRestaurant
13390       and order   BooksRestaurant
13391            wings  BooksRestaurant
13392                .  BooksRestaurant

[13393 rows x 2 columns]

In [10]:
df4 = pd.read_json("../Data/Intent/nlu-benchmark-master/2017-06-custom-intent-engines/GetWeather/train_GetWeather_full.json" ,  encoding="utf-8")
df4

                                             GetWeather
0     {'data': [{'text': 'What will the weather be '...
1     {'data': [{'text': 'Will it be '}, {'text': 's...
2     {'data': [{'text': 'Is it supposed to '}, {'te...
3     {'data': [{'text': 'what is the forecast start...
4     {'data': [{'text': 'how '}, {'text': 'cold', '...
...                                                 ...
1995  {'data': [{'text': 'What's the forecast for '}...
1996  {'data': [{'text': 'What is the weather suppos...
1997  {'data': [{'text': 'Will it get '}, {'text': '...
1998  {'data': [{'text': 'Tell me the weather foreca...
1999  {'data': [{'text': 'What is the weather foreca...

[2000 rows x 1 columns]

In [11]:
def extract(text , label):
    texts=[]
    for text in df4['GetWeather']:
        for txt in text['data']:
             texts.append(txt['text'])
    return pd.DataFrame({"text": texts , 'label':label})

df4_clean = extract(df4, "GetWeather")
df4_clean

                                             text       label
0                       What will the weather be   GetWeather
1                                       this year  GetWeather
2                                             in   GetWeather
3     Horseshoe Lake State Fish and Wildlife Area  GetWeather
4                                               ?  GetWeather
...                                           ...         ...
9840                                      Georgia  GetWeather
9841         What is the weather forecast for my   GetWeather
9842                                 current spot  GetWeather
9843                                          on   GetWeather
9844                             Jan. third, 2036  GetWeather

[9845 rows x 2 columns]

In [12]:
df4_clean = extract(df4, "GetWeather")
df4_clean

                                             text       label
0                       What will the weather be   GetWeather
1                                       this year  GetWeather
2                                             in   GetWeather
3     Horseshoe Lake State Fish and Wildlife Area  GetWeather
4                                               ?  GetWeather
...                                           ...         ...
9840                                      Georgia  GetWeather
9841         What is the weather forecast for my   GetWeather
9842                                 current spot  GetWeather
9843                                          on   GetWeather
9844                             Jan. third, 2036  GetWeather

[9845 rows x 2 columns]

In [13]:
df5 = pd.read_json("../Data/Intent/nlu-benchmark-master/2017-06-custom-intent-engines/PlayMusic/train_PlayMusic_full.json" ,  encoding="latin-1")
df5

                                              PlayMusic
0     {'data': [{'text': 'I need to hear the '}, {'t...
1     {'data': [{'text': 'play '}, {'text': 'Yo Ho',...
2     {'data': [{'text': 'Play some '}, {'text': 'se...
3     {'data': [{'text': 'play the '}, {'text': 'MÃº...
4     {'data': [{'text': 'Play '}, {'text': 'Magic S...
...                                                 ...
1995  {'data': [{'text': 'Play the '}, {'text': 'mos...
1996  {'data': [{'text': 'Play some '}, {'text': 'go...
1997  {'data': [{'text': 'play '}, {'text': '2007', ...
1998  {'data': [{'text': 'Play a '}, {'text': 'balla...
1999  {'data': [{'text': 'play '}, {'text': 'Roy Orb...

[2000 rows x 1 columns]

In [14]:
def extract(text , label):
    texts=[]
    for text in df5['PlayMusic']:
        for txt in text['data']:
             texts.append(txt['text'])
    return pd.DataFrame({"text": texts , 'label':label})

df5_clean = extract(df4, "PlayMusic")
df5_clean

                     text      label
0     I need to hear the   PlayMusic
1                    song  PlayMusic
2                          PlayMusic
3             Aspro Mavro  PlayMusic
4                   from   PlayMusic
...                   ...        ...
9409                  on   PlayMusic
9410         Google Music  PlayMusic
9411                play   PlayMusic
9412          Roy Orbison  PlayMusic
9413            tunes now  PlayMusic

[9414 rows x 2 columns]

In [15]:
df6 = pd.read_json("../Data/Intent/nlu-benchmark-master/2017-06-custom-intent-engines/RateBook/train_RateBook_full.json" ,  encoding="latin-1")
df6

                                               RateBook
0     {'data': [{'text': 'rate '}, {'text': 'The Lot...
1     {'data': [{'text': 'Rate '}, {'text': 'The Fal...
2     {'data': [{'text': 'Rate the '}, {'text': 'cur...
3     {'data': [{'text': 'rate '}, {'text': 'The Ape...
4     {'data': [{'text': 'I give '}, {'text': 'The P...
...                                                 ...
1951  {'data': [{'text': 'rate '}, {'text': 'this', ...
1952  {'data': [{'text': 'give '}, {'text': '5', 'en...
1953  {'data': [{'text': 'Give '}, {'text': 'Drift: ...
1954  {'data': [{'text': 'give '}, {'text': '1', 'en...
1955  {'data': [{'text': 'Rate '}, {'text': 'this', ...

[1956 rows x 1 columns]

In [16]:
def extract(text , label):
    texts=[]
    for text in df6['RateBook']:
        for txt in text['data']:
             texts.append(txt['text'])
    return pd.DataFrame({"text": texts , 'label':label})

df6_clean = extract(df4, "RateBook")
df6_clean

                          text     label
0                        rate   RateBook
1      The Lotus and the Storm  RateBook
2                               RateBook
3                         zero  RateBook
4                          of   RateBook
...                        ...       ...
15021                     zero  RateBook
15022                           RateBook
15023                    stars  RateBook
15024                  out of   RateBook
15025                        6  RateBook

[15026 rows x 2 columns]

In [17]:
df7 =  pd.read_json("../Data/Intent/nlu-benchmark-master/2017-06-custom-intent-engines/SearchCreativeWork/train_SearchCreativeWork_full.json" ,  encoding="latin-1")
df7

                                     SearchCreativeWork
0     {'data': [{'text': 'find the '}, {'text': 'sou...
1     {'data': [{'text': 'find a '}, {'text': 'book'...
2     {'data': [{'text': 'find the '}, {'text': 'pic...
3     {'data': [{'text': 'show creative work of '}, ...
4     {'data': [{'text': 'Where can I watch the '}, ...
...                                                 ...
1949  {'data': [{'text': 'find '}, {'text': 'The Fam...
1950  {'data': [{'text': 'look for the '}, {'text': ...
1951  {'data': [{'text': 'find the '}, {'text': 'mov...
1952  {'data': [{'text': 'find the '}, {'text': 'pho...
1953  {'data': [{'text': 'Find a '}, {'text': 'video...

[1954 rows x 1 columns]

In [18]:
def extract(text , label):
    texts=[]
    for text in df7['SearchCreativeWork']:
        for txt in text['data']:
             texts.append(txt['text'])
    return pd.DataFrame({"text": texts , 'label':label})

df7_clean = extract(df7, "SearchCreativeWork")
df7_clean

                          text               label
0                    find the   SearchCreativeWork
1                   soundtrack  SearchCreativeWork
2                      titled   SearchCreativeWork
3        This Side of Paradise  SearchCreativeWork
4                      find a   SearchCreativeWork
...                        ...                 ...
7398                   Find a   SearchCreativeWork
7399                video game  SearchCreativeWork
7400                   called   SearchCreativeWork
7401  The Last American Virgin  SearchCreativeWork
7402                         .  SearchCreativeWork

[7403 rows x 2 columns]

In [19]:
df8 = pd.read_json("../Data/Intent/nlu-benchmark-master/2017-06-custom-intent-engines/SearchScreeningEvent/train_SearchScreeningEvent_full.json" ,  encoding="latin-1")
df8

                                   SearchScreeningEvent
0     {'data': [{'text': 'What are the '}, {'text': ...
1     {'data': [{'text': 'I want to get the '}, {'te...
2     {'data': [{'text': 'Show me movie time for '},...
3     {'data': [{'text': 'Find time for '}, {'text':...
4     {'data': [{'text': 'Please show me the '}, {'t...
...                                                 ...
1954  {'data': [{'text': 'Can a I get the movie '}, ...
1955  {'data': [{'text': 'Find '}, {'text': 'movie s...
1956  {'data': [{'text': 'what time is '}, {'text': ...
1957  {'data': [{'text': 'in the neighbourhood', 'en...
1958  {'data': [{'text': 'What '}, {'text': 'cinema'...

[1959 rows x 1 columns]

In [20]:
def extract(text , label):
    texts=[]
    for text in df8['SearchScreeningEvent']:
        for txt in text['data']:
             texts.append(txt['text'])
    return pd.DataFrame({"text": texts , 'label':label})

df8_clean = extract(df4, "SearchingScreeningEvent")
df8_clean

                    text                    label
0          What are the   SearchingScreeningEvent
1         movie schedule  SearchingScreeningEvent
2                    at   SearchingScreeningEvent
3         Malco Theatres  SearchingScreeningEvent
4     I want to get the   SearchingScreeningEvent
...                  ...                      ...
9448              cinema  SearchingScreeningEvent
9449            has the   SearchingScreeningEvent
9450             closest  SearchingScreeningEvent
9451                      SearchingScreeningEvent
9452              movies  SearchingScreeningEvent

[9453 rows x 2 columns]

In [21]:
final_df = pd.concat([df1, df2_clean, df3_clean, df4_clean, df5_clean, df6_clean, df7_clean, df8_clean],ignore_index=True)

In [22]:
final_df

,text,label
0,when modi promised “minimum government maximum...,-1.0
1,talk all the nonsense and continue all the dra...,0.0
2,what did just say vote for modi welcome bjp t...,1.0
3,asking his supporters prefix chowkidar their n...,1.0
4,answer who among these the most powerful world...,1.0
...,...,...
239229,cinema,SearchingScreeningEvent
239230,has the,SearchingScreeningEvent
239231,closest,SearchingScreeningEvent
239232,,SearchingScreeningEvent
239233,movies,SearchingScreeningEvent

In [23]:
final_df.isnull().sum()

text     4
label    7
dtype: int64

In [24]:
new_df = final_df[['text' , 'label']]
new_df

,text,label
0,when modi promised “minimum government maximum...,-1.0
1,talk all the nonsense and continue all the dra...,0.0
2,what did just say vote for modi welcome bjp t...,1.0
3,asking his supporters prefix chowkidar their n...,1.0
4,answer who among these the most powerful world...,1.0
...,...,...
239229,cinema,SearchingScreeningEvent
239230,has the,SearchingScreeningEvent
239231,closest,SearchingScreeningEvent
239232,,SearchingScreeningEvent
239233,movies,SearchingScreeningEvent

In [25]:
new_df.isnull().sum()

text     4
label    7
dtype: int64

In [26]:
new_df.fillna(method='ffill' , inplace=True)

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_14908\3470422491.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df.fillna(method='ffill' , inplace=True)

In [27]:
new_df.isnull().sum()

text     0
label    0
dtype: int64

### NLP

In [28]:
nlp = spacy.load("en_core_web_sm" , disable=['parser' , 'ner'])

In [29]:
new_df

,text,label
0,when modi promised “minimum government maximum...,-1.0
1,talk all the nonsense and continue all the dra...,0.0
2,what did just say vote for modi welcome bjp t...,1.0
3,asking his supporters prefix chowkidar their n...,1.0
4,answer who among these the most powerful world...,1.0
...,...,...
239229,cinema,SearchingScreeningEvent
239230,has the,SearchingScreeningEvent
239231,closest,SearchingScreeningEvent
239232,,SearchingScreeningEvent
239233,movies,SearchingScreeningEvent

In [30]:
new_df['text'] = new_df['text'].str.lower()
new_df['text']

0         when modi promised “minimum government maximum...
1         talk all the nonsense and continue all the dra...
2         what did just say vote for modi  welcome bjp t...
3         asking his supporters prefix chowkidar their n...
4         answer who among these the most powerful world...
                                ...
239229                                               cinema
239230                                             has the
239231                                              closest
239232
239233                                               movies
Name: text, Length: 239234, dtype: object

In [31]:
new_df['text'] = new_df['text'].str.strip()
new_df['text']

0         when modi promised “minimum government maximum...
1         talk all the nonsense and continue all the dra...
2         what did just say vote for modi  welcome bjp t...
3         asking his supporters prefix chowkidar their n...
4         answer who among these the most powerful world...
                                ...
239229                                               cinema
239230                                              has the
239231                                              closest
239232
239233                                               movies
Name: text, Length: 239234, dtype: object

#### Tokenization

In [32]:
# for token in new_df['text']:
#     print(token)

#### Stop Word Removal & Punctuation

In [33]:
# for token in new_df['text']:
#     doc = nlp(token)
#     for token in doc:
#         if token.is_stop == False:
#             print(token)

In [34]:
# def removal_punctuation():
#     texts = new_df['text'].to_list()

#     docs = nlp.pipe(texts, batch_size=10000)
#     for doc in docs:
#         for token in doc:
#             if token.is_stop == False and token.is_punct == False:
#                 print(token.text)

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",   # 🔥 removes stopwords
    max_features=5000,
    ngram_range=(1, 2)
)

x = tfidf.fit_transform(new_df["text"])

In [36]:
x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1929949 stored elements and shape (239234, 5000)>

In [37]:
new_df['label'].isnull().sum()

np.int64(0)

#### Encoding Labels

In [38]:
new_df['label']

0                            -1.0
1                             0.0
2                             1.0
3                             1.0
4                             1.0
                   ...
239229    SearchingScreeningEvent
239230    SearchingScreeningEvent
239231    SearchingScreeningEvent
239232    SearchingScreeningEvent
239233    SearchingScreeningEvent
Name: label, Length: 239234, dtype: object

In [39]:
from sklearn.preprocessing import LabelEncoder

In [40]:
le = LabelEncoder()

In [41]:
# new_df = new_df.dropna(subset=["label"])

In [42]:
new_df["label"].apply(type).value_counts()

label
<class 'float'>    162980
<class 'str'>       76254
Name: count, dtype: int64

In [43]:
new_df['label'].isnull().sum()

np.int64(0)

In [44]:
new_df['label'].apply(type).value_counts()

label
<class 'float'>    162980
<class 'str'>       76254
Name: count, dtype: int64

In [45]:
new_df['label'] = new_df['label'].astype(str)
new_df['label']

0                            -1.0
1                             0.0
2                             1.0
3                             1.0
4                             1.0
                   ...
239229    SearchingScreeningEvent
239230    SearchingScreeningEvent
239231    SearchingScreeningEvent
239232    SearchingScreeningEvent
239233    SearchingScreeningEvent
Name: label, Length: 239234, dtype: object

In [46]:
x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1929949 stored elements and shape (239234, 5000)>

In [47]:
y = le.fit_transform(new_df['label'])
y

array([0, 1, 2, ..., 9, 9, 9], shape=(239234,))

In [48]:
le.classes_

array(['-1.0', '0.0', '1.0', 'AddToPlaylist', 'BooksRestaurant',
       'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork',
       'SearchingScreeningEvent'], dtype=object)

###  Intent Model Training

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2 , random_state=42)

In [51]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((191387, 5000), (47847, 5000), (191387,), (47847,))

### Logistic Regression

In [52]:
from sklearn.linear_model import LogisticRegression

In [53]:
lr = LogisticRegression()

In [54]:
lr.fit(x_train , y_train)

C:\Users\VICTUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [55]:
y_pred = lr.predict(x_test)
y_pred

array([2, 2, 7, ..., 0, 1, 2], shape=(47847,))

#### Model Evaluation

In [56]:
from sklearn.metrics import accuracy_score , f1_score

In [57]:
accuracy_score(y_pred , y_test)

0.7093234685560224

In [58]:
f1_score(y_pred , y_test , average='micro')

0.7093234685560224

### Sentiment Model Training

In [59]:
df1

                                                     text  label
0       when modi promised “minimum government maximum...   -1.0
1       talk all the nonsense and continue all the dra...    0.0
2       what did just say vote for modi  welcome bjp t...    1.0
3       asking his supporters prefix chowkidar their n...    1.0
4       answer who among these the most powerful world...    1.0
...                                                   ...    ...
162975  why these 456 crores paid neerav modi not reco...   -1.0
162976  dear rss terrorist payal gawar what about modi...   -1.0
162977  did you cover her interaction forum where she ...    0.0
162978  there big project came into india modi dream p...    0.0
162979  have you ever listen about like gurukul where ...    1.0

[162980 rows x 2 columns]

In [60]:
df1.isnull().sum()

text     4
label    7
dtype: int64

In [61]:
df1.fillna(method='ffill' , inplace=True)

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_14908\3957927175.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill' , inplace=True)

In [62]:
df1.isnull().sum()

text     0
label    0
dtype: int64

In [63]:
df1["text"] = df1["text"].astype(str)
df1["label"] = df1["label"].astype(str)

In [64]:
from sklearn.preprocessing import LabelEncoder

In [65]:
sentiment_le = LabelEncoder()

In [66]:
y = sentiment_le.fit_transform(df1['label'])
y

array([0, 1, 2, ..., 1, 1, 2], shape=(162980,))

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",   # 🔥 removes stopwords
    max_features=7000,
    ngram_range=(1, 2)
)

x = tfidf.fit_transform(df1["text"])

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
x_train , x_test , y_train , y_test = train_test_split(x , y  , test_size=0.2 , random_state=42)

In [70]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((130384, 7000), (32596, 7000), (130384,), (32596,))

### Logistic Regression

In [71]:
from sklearn.linear_model import LogisticRegression

In [72]:
sent_lr = LogisticRegression()

In [73]:
sent_lr.fit(x_train , y_train)

C:\Users\VICTUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [74]:
y_pred = sent_lr.predict(x_test)
y_pred

array([1, 1, 2, ..., 2, 0, 1], shape=(32596,))

In [75]:
y_pred_ = sentiment_le.inverse_transform(y_pred)
print(y_pred_[:10])

['0.0' '0.0' '1.0' '0.0' '0.0' '1.0' '1.0' '0.0' '0.0' '-1.0']

### Model Evaluation

In [76]:
from sklearn.metrics import accuracy_score , f1_score

In [77]:
accuracy_score(y_pred , y_test)

0.847496625352804

In [78]:
f1_score(y_pred , y_test , average='micro')

0.847496625352804

#### Saving Intent Model files

In [79]:
import joblib

In [80]:
joblib.dump(lr, "intent_model.pkl")
joblib.dump(tfidf, "tfidf.pkl")
joblib.dump(le, "label_encoder.pkl")

['label_encoder.pkl']

In [81]:
import os
os.listdir()

['01_eda.ipynb',
 '02_preprocessing.ipynb',
 '03_intent_model.ipynb',
 '04_sentiment_model.ipynb',
 'intent_model.pkl',
 'label_encoder.pkl',
 'sentiment_label_encoder.pkl',
 'sentiment_model.pkl',
 'sentiment_tfidf.pkl',
 'tfidf.pkl']

### Saving Sentiment Model Files

In [82]:
joblib.dump(sent_lr, "sentiment_model.pkl")
joblib.dump(tfidf, "sentiment_tfidf.pkl")
joblib.dump(sentiment_le, "sentiment_label_encoder.pkl")

['sentiment_label_encoder.pkl']